#mpiexec -n 1 ./XT_Main --proj_rows 16 --proj_cols 768 --proj_num 6144 --recon_num 128 --vox_wid 1.3 --rot_center 385 --sig_s 0.010413 --sig_t 0.000104 --c_s 0.000001 --c_t 0.000001 --convg_thresh 1 --remove_rings 1 --remove_streaks 1  

cd $PBS_O_WORKDIR
module load devel
module load valgrind
export PARALLEL=1
export OMP_NUM_THREADS=32

# Arguments for simulated data generated by MBIR forward projector
./XT_Main --proj_rows 128 --proj_cols 128 --proj_x_num 71 --proj_y_num 71 --vox_wid 0.5 --qggmrf_sigma 0.000005 --qggmrf_c 0.00000001 --convg_thresh 0.5 --admm_mu 500000000 --admm_maxiters 100 --x_widnum 128 --y_widnum 128 --z_widnum 128 --data_variance 0.00001

checkjob -v $PBS_JOBID
